#!/usr/bin/env bash
cd "$(dirname "$0")" || exit 1
# ---
cd ../www || exit 1

NODE=(./.gradle/nodejs/node*/bin/node)
[ "${#NODE[@]}" -ne 1 ] && { echo 'Multiple matches' >&2; exit 1; }

"${NODE[0]}" ./src/main.js